const char* PLAYER1_IMG =
    "KKKKKKKKKKK"
    "KKKDDDDDKKK"
    "KKKRRRRRKKK"
    "KKKSKSKSKKK"
    "KKKSSSSSKKK"
    "KKKSSSSSKKK"
    "KKYYRRRYYKK"
    "KKKKRRRKKKK"
    "KKKKRRRKKKK"
    "KKKKYKYKKKK"
    "KKKKYKYKKKK";

const char* PLAYER1_ATK =
    "KKKKKKKKKKK"
    "KDDDDDKKRKK"
    "KRRRRRKKRKK"
    "KSKSKSKKRKK"
    "KSSSSSKKRKK"
    "KSSSSSKKRKK"
    "KYRRRYYRRRK"
    "KKRRRKKKRKK"
    "KKRRRKKKKKK"
    "KKYKYKKKKKK"
    "KKYKYKKKKKK";

const char* PLAYER1_WALK =
    "KKKKKKKKKKK"
    "KKKDDDDDKKK"
    "KKKRRRRRKKK"
    "KKKSKSKSKKK"
    "KKKSSSSSKKK"
    "KKKSSSSSKKK"
    "KKKYYRRYYKK"
    "KKKKRRRKKKK"
    "KKKKRYRYKKK"
    "KKKKKYKYKKK"
    "KKKKKKKKKKK";

const char* PLAYER2_IMG =
    "KKKKKKKKKKK"
    "KKKDDDDDKKK"
    "KKKBBBBBKKK"
    "KKKSKSKSKKK"
    "KKKSSSSSKKK"
    "KKKSSSSSKKK"
    "KKGGBBBGGKK"
    "KKKKBBBKKKK"
    "KKKKBBBKKKK"
    "KKKKGKGKKKK"
    "KKKKGKGKKKK";

const char* PLAYER2_ATK =
    "KKKKKKKKKKK"
    "KKKKKDDDDDK"
    "KKKKKBBBBBK"
    "KKKKKSKSKSK"
    "KKKKKSSSSSK"
    "KR555BBSSSK"
    "KR5555555GK"
    "KKK5555555K"
    "KKKKKKBBBKK"
    "KKKKKKGKGKK"
    "KKKKKKGKGKK";

const char* PLAYER2_WALK =
    "KKKKKKKKKKK"
    "KKKDDDDDKKK"
    "KKKBBBBBKKK"
    "KKKSKSKSKKK"
    "KKKSSSSSKKK"
    "KKKSSSSSKKK"
    "KKKGGBBGGKK"
    "KKKKBBBKKKK"
    "KKKKBGBGKKK"
    "KKKKKGKGKKK"
    "KKKKKKKKKKK";

const char* PLANT_IMG =
    "KKKKKKKKKKK"
    "KKGGGGGGGKK"
    "KGGGGGGRGGK"
    "KGGRGGGGGGK"
    "KGGGGGGGGGK"
    "KGGGGRGGGGK"
    "KKGGGGGGGKK"
    "KKKKDDDKKKK"
    "KKKKDDDKKKK"
    "KKKKDDDKKKK"
    "KKKKDDDKKKK";

const char* PLANT_IMG2 =
    "KKKKKKKKKKK"
    "KGGGGGGKKKK"
    "GGGGGGGKKKK"
    "GGGGGGGGKKK"
    "GGGGGGGGKKK"
    "GGGRGGGGKKK"
    "KGGGGGKKKKK"
    "KKDDDKKRKKK"
    "KKKDDKKKKKK"
    "KRKDDDKKKKK"
    "KKKKDDDKKKK";

const char* WALL_IMG =
    "DD55DD55DD5"
    "D55DD55DD55"
    "55DD55DD55D"
    "5DD55DD55DD"
    "DD55DD55DD5"
    "D55DD55DD55"
    "55DD55DD55D"
    "5DD55DD55DD"
    "DD55DD55DD5"
    "D55DD55DD55"
    "55DD55DD55D";

const char* ROCK_IMG =
    "KKKKKKKKKKK"
    "KKKKKKKKKKK"
    "KKKKKKKKKKK"
    "KKKK555KKKK"
    "KKK55555KKK"
    "KKK555555KK"
    "KK5555555KK"
    "KK55555555K"
    "KK55555555K"
    "K555555555K"
    "K555555555K";

const char* ROCK_IMG2 =
    "KKKKKKKKKKK"
    "KDDKKKKKDDK"
    "KDSDDKKDSDK"
    "KDSS555DSDK"
    "KDS55555SDK"
    "KKD5K5K55DK"
    "KK55K5K55KK"
    "KK55555555K"
    "KK5S555S55K"
    "K555SSS555K"
    "K555555555K";

const char* POTION_IMG =
    "KKKKKYKKKKK"
    "KKKKYYYKKKK"
    "KKKWWYWWKKK"
    "KKKKWYWKKKK"
    "KKKKWGWKKKK"
    "KKKWGGGWKKK"
    "KKWGGGGGWKK"
    "KKWGGGGGWKK"
    "KWGGGGGGGWK"
    "KWGGGGGGGWK"
    "KWWWWWWWWWK";

const char* FOOTSTEP_IMG =
    "KKKKKKKKKKK"
    "KKKKKDKKKKK"
    "KDDKDDDKDDK"
    "KDDKDDDKDDK"
    "KKKKKKKKKKK"
    "KKKKDDDKKKK"
    "KKKDDDDDKKK"
    "KKDDDDDDDKK"
    "KKDDDDDDDKK"
    "KKDDDDDDDKK"
    "KKKDDDDDKKK";
