const char* PLAYER1_IMG =
    "KKKKKKKKKKK"
    "KKKDDDDDKKK"
    "KKKRRRRRKKK"
    "KKKSKSKSKKK"
    "KKKSSSSSKKK"
    "KKKSSSSSKKK"
    "KKYYRRRYYKK"
    "KKKKRRRKKKK"
    "KKKKRRRKKKK"
    "KKKKYKYKKKK"
    "KKKKYKYKKKK";

const char* PLAYER2_IMG =
    "KKKKKKKKKKK"
    "KKKDDDDDKKK"
    "KKKBBBBBKKK"
    "KKKSKSKSKKK"
    "KKKSSSSSKKK"
    "KKKSSSSSKKK"
    "KKGGBBBGGKK"
    "KKKKBBBKKKK"
    "KKKKBBBKKKK"
    "KKKKGKGKKKK"
    "KKKKGKGKKKK";

const char* PLANT_IMG =
    "KKKKKKKKKKK"
    "KKGGGGGGGKK"
    "KGGGGGGRGGK"
    "KGGRGGGGGGK"
    "KGGGGGGGGGK"
    "KGGGGRGGGGK"
    "KKGGGGGGGKK"
    "KKKKDDDKKKK"
    "KKKKDDDKKKK"
    "KKKKDDDKKKK"
    "KKKKDDDKKKK";

const char* WALL_IMG =
    "DD55DD55DD5"
    "D55DD55DD55"
    "55DD55DD55D"
    "5DD55DD55DD"
    "DD55DD55DD5"
    "D55DD55DD55"
    "55DD55DD55D"
    "5DD55DD55DD"
    "DD55DD55DD5"
    "D55DD55DD55"
    "55DD55DD55D";

const char* ROCK_IMG =
    "KKKKKKKKKKK"
    "KKKKKKKKKKK"
    "KKKKKKKKKKK"
    "KKKK555KKKK"
    "KKK55555KKK"
    "KKK555555KK"
    "KK5555555KK"
    "KK55555555K"
    "KK55555555K"
    "K555555555K"
    "K555555555K";

const char* POTION_IMG =
    "KKKKKYKKKKK"
    "KKKKYYYKKKK"
    "KKKWWYWWKKK"
    "KKKKWYWKKKK"
    "KKKKWGWKKKK"
    "KKKWGGGWKKK"
    "KKWGGGGGWKK"
    "KKWGGGGGWKK"
    "KWGGGGGGGWK"
    "KWGGGGGGGWK"
    "KWWWWWWWWWK";